image: python:latest

cache:
  paths:
  - ~/.cache/pip/

stages:
  - build

Style check:
  stage: build
  tags:
    - shared-fi
  before_script:
    - python -V
    - pip install -U pip
    - pip install .
    - pip install flake8
  script:
    - flake8

Type check:
  stage: build
  tags:
    - shared-fi
  before_script:
    - python -V
    - pip install -U pip
    - pip install .
    - pip install pytype>=2021
  script:
    - pytype .

Unit tests:
  stage: build
  tags:
    - shared-fi
  before_script:
    - python -V
    - pip install -U pip
    - pip install .
  script:
    - python setup.py test
